import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";

const host = Geist_Mono({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Adhvaidh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${host.className} bg-black antialiased`}>
        {children}
      </body>
    </html>
  );
}
